//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.13.1+667c2f5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, ICommonContentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Header: Choose background color for header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("backgroundHeader")]
		public virtual decimal BackgroundHeader => this.Value<decimal>(_publishedValueFallback, "backgroundHeader");

		///<summary>
		/// Background Menu: Choose background color for menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("backgroundMenu")]
		public virtual decimal BackgroundMenu => this.Value<decimal>(_publishedValueFallback, "backgroundMenu");

		///<summary>
		/// Color Menu: Choose color for menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("colorMenu")]
		public virtual decimal ColorMenu => this.Value<decimal>(_publishedValueFallback, "colorMenu");

		///<summary>
		/// Company Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyCode")]
		public virtual string CompanyCode => this.Value<string>(_publishedValueFallback, "companyCode");

		///<summary>
		/// Company Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "companyLogo");

		///<summary>
		/// Copyright
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("copyright")]
		public virtual string Copyright => this.Value<string>(_publishedValueFallback, "copyright");

		///<summary>
		/// Developed Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("developedLink")]
		public virtual decimal DevelopedLink => this.Value<decimal>(_publishedValueFallback, "developedLink");

		///<summary>
		/// Footer Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "footerLogo");

		///<summary>
		/// Header Height: Height of header. Unit is rem.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("headerHeight")]
		public virtual decimal HeaderHeight => this.Value<decimal>(_publishedValueFallback, "headerHeight");

		///<summary>
		/// Header Mobile: Select type of header mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerMobile")]
		public virtual string HeaderMobile => this.Value<string>(_publishedValueFallback, "headerMobile");

		///<summary>
		/// Header Sticky: Enable/disable header sticky in your page, and select type of sticky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerSticky")]
		public virtual string HeaderSticky => this.Value<string>(_publishedValueFallback, "headerSticky");

		///<summary>
		/// Hidden Developed By
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("hiddenDevelopedBy")]
		public virtual bool HiddenDevelopedBy => this.Value<bool>(_publishedValueFallback, "hiddenDevelopedBy");

		///<summary>
		/// Home Page Logo Url: Change the default url address for the logo image on the homepage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("homePageLogoUrl")]
		public virtual global::Umbraco.Cms.Core.Models.Link HomePageLogoUrl => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "homePageLogoUrl");

		///<summary>
		/// Language: Enable/disable language
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("language")]
		public virtual bool Language => this.Value<bool>(_publishedValueFallback, "language");

		///<summary>
		/// Link Linkedin
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkLinkedin")]
		public virtual global::Umbraco.Cms.Core.Models.Link LinkLinkedin => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "linkLinkedin");

		///<summary>
		/// Link X
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkX")]
		public virtual global::Umbraco.Cms.Core.Models.Link LinkX => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "linkX");

		///<summary>
		/// List Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("listAddress")]
		public virtual decimal ListAddress => this.Value<decimal>(_publishedValueFallback, "listAddress");

		///<summary>
		/// List Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("listEmail")]
		public virtual decimal ListEmail => this.Value<decimal>(_publishedValueFallback, "listEmail");

		///<summary>
		/// Logo Width: Arrange width of logo between 100 to 500px. However, still limited by image size.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("logoWidth")]
		public virtual decimal LogoWidth => this.Value<decimal>(_publishedValueFallback, "logoWidth");

		///<summary>
		/// Menu Mobile Location: Select location of menu on mobile. The setting only works when the header mobile is center
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuMobileLocation")]
		public virtual string MenuMobileLocation => this.Value<string>(_publishedValueFallback, "menuMobileLocation");

		///<summary>
		/// Menu Mobile Style: Choose style of mobile menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuMobileStyle")]
		public virtual string MenuMobileStyle => this.Value<string>(_publishedValueFallback, "menuMobileStyle");

		///<summary>
		/// Mobile Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mobileLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MobileLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "mobileLogo");

		///<summary>
		/// Note Analytics
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("noteAnalytics")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString NoteAnalytics => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "noteAnalytics");

		///<summary>
		/// Note Cookies
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("noteCookies")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString NoteCookies => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "noteCookies");

		///<summary>
		/// QR Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("qRCode")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops QRcode => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "qRCode");

		///<summary>
		/// Search: Enable/disable search
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[ImplementPropertyType("search")]
		public virtual bool Search => this.Value<bool>(_publishedValueFallback, "search");

		///<summary>
		/// Ticker Scroll Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tickerScrollName")]
		public virtual string TickerScrollName => this.Value<string>(_publishedValueFallback, "tickerScrollName");

		///<summary>
		/// Ticker Scroll Version
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tickerScrollVersion")]
		public virtual string TickerScrollVersion => this.Value<string>(_publishedValueFallback, "tickerScrollVersion");

		///<summary>
		/// URL Tools
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("urlTools")]
		public virtual string UrlTools => this.Value<string>(_publishedValueFallback, "urlTools");

		///<summary>
		/// Mega Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("megaContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString MegaContent => global::Umbraco.Cms.Web.Common.PublishedModels.CommonContentBase.GetMegaContent(this, _publishedValueFallback);

		///<summary>
		/// Page English Title: The page title in english language
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageEnglishTitle")]
		public virtual string PageEnglishTitle => global::Umbraco.Cms.Web.Common.PublishedModels.CommonContentBase.GetPageEnglishTitle(this, _publishedValueFallback);

		///<summary>
		/// Page Title: The title of the page, this is also the first text in a google search result. The ideal length is between 40 and 60 characters
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.13.1+667c2f5")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.CommonContentBase.GetPageTitle(this, _publishedValueFallback);
	}
}
